config/routes.rb
Estimating::Application.routes.draw do

	root :to => "static#index"
  match 'how_it_works' => 'static#how_it_works'
  match 'info/:action' => 'static'
  match 'sitemap.xml' => 'static#sitemap'

  match 'index(/:category_key)' => 'site#index', :as => :index, :category_key => /.+/
  match 'request_detail/:id' => 'site#request_detail', :as => :request_detail
  match 'proposal_submission' => 'site#proposal_submission', :as => :proposal_submission
  match 'proposal_new/:id' => 'site#proposal_new', :as => :proposal_new

  resources :requests
  match 'personal_index' => 'requests#personal_index'
  match 'search_requests' => 'requests#search'
  match 'set_best_proposal' => 'requests#set_best_proposal', :as => :set_best_proposal, :via => :post

  resources :proposals

  resources :favourite_categories
  match 'interesting_requests' => 'favourite_categories#interesting_requests', :as => :interesting_requests

  resources :users
  resources :user_sessions
	match 'login' => 'user_sessions#new'
	match 'logout' => 'user_sessions#destroy'
  match 'activation' => 'user_sessions#activation' # Shows the form in which the user could paste the activation code
  match 'activate' => 'user_sessions#activate' # Activate the account
  match 'lost_password' => 'users#lost_password'
  match 'require_reset_password_token' => 'users#require_reset_password_token' # Send an email with info about how to reset the pwd
  match 'confirm_password_reset' => 'users#confirm_password_reset'
  match 'password_reset' => 'users#password_reset'

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |conf|
    conf.maintain_sessions= false
  end

  has_many :proposals
  has_many :requests
  has_many :favourite_categories

  attr_accessor :eula, :privacy
  
  validates_presence_of :first_name, :last_name, :address, :city
  validates_format_of   :vat, :with => /\d{11}/, :if => :is_professional?
  validates_presence_of :company_name, :if => :is_professional?
  validates_presence_of :activity, :if => :is_professional?
  validates_format_of :zip, :with => /\d{5}/
  validates_acceptance_of :eula, :privacy

  #  def after_initialize
  #    self.is_professional=true
  #  end

#  def self.find_by_verified_login(login)
#    user = find_by_smart_case_login_field(login)
#    user.is_verified ? user : nil
#  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @user.is_professional = false
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # POST /users
  # POST /users.xml
  def create

    @user = User.new(params[:user])

    if( params[:email_confirmation].nil? || params[:email_confirmation] != params[:user][:email])
      flash.now[:error]= "La mail di conferma non corrisponde."
      render :action => :new
      return
    end

    if params[:user][:eula]=="1"
      @user.last_eula_confirmation = DateTime.now
    end
    if params[:user][:privacy]=="1"
      @user.last_privacy_confirmation = DateTime.now
    end

    if @user.save
      RegistrationMailer.registration_verification_email(@user).deliver
      flash[:notice]= "Riceverai una mail di attivazione."
      redirect_to "/"
    else
      flash.now[:error]= "Si sono verificati degli errori."
      render :action => :new
    end
  end

  # Invoked when a user lost his/her password
  def lost_password

  end

  # Invoked when a user lost his/her password
  def require_reset_password_token
    email = params[:email]
    if email.nil? || email.blank?
      flash.now[:error] = "Per favore, fornisci un indirizzo di posta elettronica."
      render :action => :lost_password
      return
    end

    user = User.find_by_email email
    if !user.nil?
      new_token = user.reset_perishable_token!
      flash.now[:notice] = "E' stata inviata una mail all'indirizzo #{user.email} con le istruzioni per il reset della password."
      RegistrationMailer.reset_password_email(user, new_token).deliver
      render :template => "users/generic.html.erb"
    else
      flash.now[:warning] = "L'indirizzo di posta elettronica '#{email}' non risulta associato ad alcun utente."
      render :action => :lost_password
    end
  end

  def confirm_password_reset
    @token = params[:activation_token]

    if @token.nil? || @token.strip.length == 0
      flash.now[:error] = "Il token non è valido."
      render :template => "users/generic.html.erb"
      return
    end

    user = User.find_by_perishable_token @token
    if user.nil?
      flash.now[:error] = "Il token non esiste."
      render :template => "users/generic.html.erb"
      return
    end

    render :action => :password_reset
    return
  end

  def password_reset
    puts '*********** 0'
    @token = params[:activation_token]

    if @token.nil? || @token.strip.length == 0
      flash.now[:error] = "Il token non è valido."
      render :template => "users/generic.html.erb"
      return
    end

    user = User.find_by_perishable_token @token
    if user.nil?
      flash.now[:error] = "Il token non esiste."
      render :template => "users/generic.html.erb"
      return
    end

    new_password = params[:password]
    password_confirmation = params[:password_confirmation]

    puts "zappala: #{new_password} / #{password_confirmation}"

    if !new_password.nil? && new_password==password_confirmation
      user.password = new_password
      user.password_confirmation = password_confirmation
      if user.save
        flash.now[:notice] = "La password è stata cambiata."
        render :template => "users/generic.html.erb"
        return
      end
    else
      flash.now[:error] = "La password non corrisponde."
      render :action => :password_reset
      return
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/generic.html.erb
<%= link_to "Torna alla home", root_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/lost_password.html.erb
<% @page_title = titlize("Richiesta nuova password")  %>

Hai dimenticato la tua password ? Ecco la procedura da seguire per ottenere una nuova password.
<ol>
  <li>Inserisci l'indirizzo di posta elettronica che hai fornito in fase di registrazione.</li>
  <li>Riceverai da MiServe una mail con un codice di conferma di ridefinizione della password.</li>
  <li>Clicca sul codice per confermare la tua richiesta di ridefinizione della password.</li>
  <li>Specifica la tua nuova password.</li>
</ol>

<%= form_tag(require_reset_password_token_path, :method=>:post, :class=>:pretty) do %>
  <fieldset>
    <legend>Codice di attivazione.</legend>
    <div class="required">
      <%=label_tag :email, "E-mail"%>
      <%=text_field_tag :email%>
      <small>L'indirizzo di posta elettronica che hai fornito in fase di registrazione.</small>
    </div>
  </fieldset>
  <input type="submit" value="Richiedi il codice di ridefinizione della password"/>
<% end%>

app/views/users/new.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    
    function updateView(){

      var checkbox =  $j('#user_is_professional_true');
      var isProfessional = checkbox.attr("checked");

      if(isProfessional){
        $j('#user_vat').removeAttr("disabled");
        $j('#user_company_name').removeAttr("disabled");
        $j('#user_activity').removeAttr("disabled");
      }else{
        $j('#user_vat').attr("disabled", "disabled");
        $j('#user_company_name').attr("disabled", "disabled");
        $j('#user_activity').attr("disabled", "disabled");
      }

    }

    $j(document).ready(function(){
        var professional_yes = $j("#user_is_professional_true");
        var professional_no = $j("#user_is_professional_false");

        professional_yes.click(updateView);
        professional_no.click(updateView);

        updateView();
    });
  </script>
<% end %>

<!--
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('generic.error.form') %></h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
-->

<% content_for :layout_side_two do %>
  <%= render :partial => 'shared/default_side_two' %>
<% end %>

<%= form_for(@user, :html=>{:class=>'pretty'}) do |f| %>

  <fieldset>
    <legend>1. Account</legend>
    <div class="notes">
      <h4>Nuovo Account</h4>
      <p>
        Scegli uno username e una password per accedere al sito.
      </p>
      <p class="last">
        E' importante che tu fornisca un indirizzo di posta elettronica valido e 
        funzionante a cui hai accesso poichè vi riceverai una mail
        con il codice di attivazione necessario all'attivazione
        del tuo nuovo account.
      </p>
    </div>
    <div class="required">
      <%= f.label :login, 'Login:' %>
      <%= f.text_field :login, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:login].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :password, 'Password:' %>
      <%= f.password_field :password, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:password].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :password_confirmation, 'Conferma Password:' %>
      <%= f.password_field :password_confirmation, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:password_confirmation].join(". ") %></small>
      <small>Immetti nuovamente la password.</small>
    </div>

    <div class="required">
      <%= f.label :email, 'Email:' %>
      <%= f.email_field :email, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:email].join(". ") %></small>
    </div>

    <div class="required">
      <%= label_tag :email_confirmation, 'Conferma Email:' %>
      <%= email_field_tag :email_confirmation, nil, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:email_confirmation].join(". ") %></small>
      <small>Immetti nuovamente la mail.</small>
    </div>
  </fieldset>


  <fieldset>
    <legend>2. Dati Anagrafici</legend>
    <div class="notes">
      <h4>Dati Anagrafici</h4>
      <p class="last">
        I dati personali che ci fornirai saranno
        forniti esclusivamente agli operatori e ai
        fornitori con il quale concluderai positivamente
        una richiesta.
      </p>
    </div>

    <div class="required">
      <%= f.label :first_name, 'Nome:' %>
      <%= f.text_field :first_name, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:first_name].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :last_name, 'Cognome:' %>
      <%= f.text_field :last_name, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:last_name].join(". ") %></small>
    </div>

    <div class="required">
      <%=  f.label :address, 'Indirizzo:' %>
      <%= f.text_field :address, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @user.errors[:address].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :zip, 'CAP:' %>
      <%= f.text_field :zip, :class=>:inputText, :size=>10, :maxlength=>5 %>
      <small class="error"><%= @user.errors[:zip].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :city, 'Città:' %>
      <%= f.text_field :city, :class=>:inputText, :size=>10, :maxlength=>10 %>
      <small class="error"><%= @user.errors[:city].join(". ") %></small>
    </div>

  </fieldset>


  <fieldset>
    <legend>3. Operatore Professionale</legend>
    <div class="notes">
      <h4>Professionalità</h4>
      <p>
        Se sei un operatore professionale
        ti chiediamo alcuni dati aggiuntivi.
      </p>
      <p class="last">
        In questo caso le tue offerte saranno evidenziate
        come provenienti da un operatore professionale.
      </p>
    </div>

    <div class="required">
      <fieldset><legend>Professionale</legend>
        
        <label for="user_is_professional_true" class="labelRadio">
          <%= f.radio_button :is_professional, true, :class=>:inputRadio %>
          Professionale
        </label>
        <label for="user_is_professional_false" class="labelRadio">
          <%= f.radio_button :is_professional, false, :class=>:inputRadio %>
          Non professionale
        </label>
        <small class="error"><%= @user.errors[:is_professional].join(". ") %></small>
        
      </fieldset>
    </div>

    <div class="required">
      <%= f.label :vat, 'Partita IVA:' %>
      <%= f.text_field :vat, :class=>:inputText, :size=>10, :maxlength=>11 %>
      <small class="error"><%= @user.errors[:vat].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :company_name, 'Ragione Sociale:' %>
      <%= f.text_field :company_name, :class=>:inputText, :size=>10, :maxlength=>128 %>
      <small class="error"><%= @user.errors[:company_name].join(". ") %></small>
    </div>

    <div class="required">
      <%= f.label :activity, 'Attività:' %>
      <%= f.text_field :activity, :class=>:inputText, :size=>10, :maxlength=>128 %>
      <small class="error"><%= @user.errors[:activity].join(". ") %></small>
    </div>

  </fieldset>

  <fieldset>
    <legend>4. Informative.</legend>

    <div class="optional">
      <%=  f.label :eula, 'Condizioni del servizio:' %>
      <%= f.check_box :eula, :class=>:checkBox %>
      Spunta per accettare le <a href="">condizioni d'uso del servizio</a>.
      <small class="error"><%= @user.errors[:eula].join(". ") %></small>
    </div>

    <div class="optional">
      <%=  f.label :privacy, 'Informativa sulla privacy:' %>
      <%= f.check_box :privacy, :class=>:checkBox %>
      Spunta per accettare <a href="">l'informativa sulla privacy</a>.
      <small class="error"><%= @user.errors[:privacy].join(". ") %></small>
    </div>

  </fieldset>

  <div class="actions">
    <%= f.submit "registrati" %>
  </div>
<% end %>

app/views/users/password_reset.html.erb
<% @page_title = titlize("Ridefinizione password di accesso")  %>

<p>
  A seguito della conferma del codice di ridefinizione della tua password,
  ti preghiamo di fornire la tua nuova password di accesso.
</p>

<%= form_tag(password_reset_path, :method=>:post, :class=>:pretty) do %>
  <%=hidden_field_tag :activation_token, @token%>
  <fieldset>
    <legend>Ridefinizione della nuova password.</legend>
    <div class="required">
      <%=label_tag :password, "Nuova Password"%>
      <%=password_field_tag :password%>
    </div>
    <div class="required">
      <%=label_tag :password_confirmation, "Conferma password"%>
      <%=password_field_tag :password_confirmation%>
    </div>
  </fieldset>
  <input type="submit" value="Conferma Nuova Password"/>
<% end%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>