config/routes.rb
Estimating::Application.routes.draw do

	root :to => "static#index"
  match 'how_it_works' => 'static#how_it_works'
  match 'info/:action' => 'static'
  match 'sitemap.xml' => 'static#sitemap'

  match 'index(/:category_key)' => 'site#index', :as => :index, :category_key => /.+/
  match 'request_detail/:id' => 'site#request_detail', :as => :request_detail
  match 'proposal_submission' => 'site#proposal_submission', :as => :proposal_submission
  match 'proposal_new/:id' => 'site#proposal_new', :as => :proposal_new

  resources :requests
  match 'personal_index' => 'requests#personal_index'
  match 'search_requests' => 'requests#search'
  match 'set_best_proposal' => 'requests#set_best_proposal', :as => :set_best_proposal, :via => :post

  resources :proposals

  resources :favourite_categories
  match 'interesting_requests' => 'favourite_categories#interesting_requests', :as => :interesting_requests

  resources :users
  resources :user_sessions
	match 'login' => 'user_sessions#new'
	match 'logout' => 'user_sessions#destroy'
  match 'activation' => 'user_sessions#activation' # Shows the form in which the user could paste the activation code
  match 'activate' => 'user_sessions#activate' # Activate the account
  match 'lost_password' => 'users#lost_password'
  match 'require_reset_password_token' => 'users#require_reset_password_token' # Send an email with info about how to reset the pwd
  match 'confirm_password_reset' => 'users#confirm_password_reset'
  match 'password_reset' => 'users#password_reset'

end

app/views/shared/_best_proposal.html.erb
<div class="box">
  <h1>
    Miglior offerta<br/>
    <small>
      <%if !best_proposal.nil? and best_proposal.request.is_active %>
        Alla scadenza della richiesta chi ha proposto questa offerta verrà messo in contatto con il richiedente.
      <%else%>
        Questa è la proposta che si è aggiudicata l'erogazione del servizio secondo le condizioni descritte.
      <%end%>
    </small>
  </h1>
  <div class="body">
    <% unless best_proposal.nil? %>
      <table>
        <tr>
          <td>Operatore</td>
          <td><%= best_proposal.user.login %></td>
        </tr>
        <tr>
          <td>Preventivo</td>
          <td><%= best_proposal.amount %> &euro;</td>
        </tr>
        <tr>
          <td>Descrizione</td>
          <td><%= best_proposal.description %></td>
        </tr>
      </table>
    <% else %>
      Per questa richiesta non è ancora stata selezionata alcuna proposta come migliore.
    <% end %>
  </div>
</div>

app/views/shared/_default_side_two.html.erb
<%# This is the default content for the side two. %>
<script type="text/javascript"><!--
google_ad_client = "pub-3109155087583260";
/* home_right_skyscraper */
google_ad_slot = "3159677978";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>


<!--
<div class="index_box">
  <h1>Consigli ?</h1>
  <div>
    Hai un'idea
    per migliorare MiServe ?
    Segnalacela!
  </div>
</div>

<div class="index_box">
  <h1>Seguici</h1>
  <div>
    <%= image_tag 'logo_fb.png' %>
    <%= image_tag 'logo_twitter.png' %>
  </div>
</div>

<%= image_tag('square_banner.png', :style => 'margin:0; padding:0') %>
<%= image_tag('square_banner.png', :style => 'margin:0; padding:0') %>
-->

app/views/shared/_footer.html.erb
<p>
Copyright &copy; 2011-<%=Time.new.year%> MiServe.
Tutti i diritti riservati.
Marchi registrati e segni distintivi sono di proprietà dei rispettivi titolari.
</p>
<p>
L'uso di questo sito web implica l'accettazione dell'
<%= link_to "Accordo per gli utenti", '/info/terms_of_service' %>
di
MiServe e delle 
<%= link_to "Regole sulla privacy", '/info/privacy_note' %>
|
<%= link_to "Site Map", '/info/site_map' %>
</p>

app/views/shared/_personal_menu.html.erb
<% if current_user %>
    <div class="menu_tree">
      <ul>
        <li>
          Strumenti per utenti
          <ul>
            <li><%= link_to "nuova richiesta", new_request_path, :class=>:first %></li>
            <li><%= link_to "richieste in preparazione (#{@draft_requests_number})", requests_path(:status => :draft), :class=>:middle %></li>
            <li><%= link_to "richieste attive (#{@active_requests_number})", requests_path(:status => :active), :class=>:middle %></li>
            <li><%= link_to "richieste scadute (#{@expired_requests_number})", requests_path(:status => :expired), :class=>:last %></li>
          </ul>
        </li>
        <li>
          Strumenti per operatori
          <ul>
            <li><%= link_to "categorie preferite", favourite_categories_path(:status => :active), :class=>:first %></li>
            <li><%= link_to "richieste interessanti", :controller => :favourite_categories, :action => :interesting_requests, :class=>:middle %></li>
            <li><%= link_to "tutte le proposte (#{@active_proposals_number})", proposals_path(:status => :active), :class=>:middle %></li>
            <li><%= link_to "proposte migliori (#{@best_proposals_number})", proposals_path(:status => :best), :class=>:middle %></li>
            <li><%= link_to "proposte aggiudicate (#{@awarded_proposals_number})", proposals_path(:status => :awarded), :class=>:middle %></li>
            <li><%= link_to "proposte perse (#{@rejected_proposals_number})", proposals_path(:status => :rejected), :class=>:last %></li>
          </ul>
        </li>
      </ul>
    </div>
<% end %>

app/views/shared/_personal_proposal.html.erb
<div class="proposal">
  <div class="details">
    <h1>
      <%= link_to "Offerta alla richiesta #{personal_proposal.request.title}", request_path(personal_proposal.request) %>
    </h1>
    <!--
    <h2><%= (current_user == personal_proposal.user) ? "è una tua offerta" : "offerta di #{personal_proposal.user.login}" %></h2>
    -->
  </div>

  <div class="description">
    <%= personal_proposal.description %><br/>
    preventivo: <%= personal_proposal.amount %> &euro;<br/>
    migliore: <%= personal_proposal.is_best ? "si" : "no" %>
  </div>
  <div class="times">
    <strong>
      <% if personal_proposal.request.is_expired %>
        <%= "scaduta da #{distance_of_time_in_words DateTime.now, personal_proposal.request.expiration}" %>
      <% else %>
        <%= "scade tra #{distance_of_time_in_words DateTime.now, personal_proposal.request.expiration}" %>
      <% end %>
    </strong>
    <%= personal_proposal.request.expiration.strftime("%d/%m/%Y %H:%M") %>
  </div>
</div>

app/views/shared/_personal_request.html.erb
<div class="request">
  <div class="picture">
    <%= image_tag "category/#{personal_request.category_id}.jpg" %>
  </div>
  <div class="details">
    <h1>
      <%= link_to personal_request.title, request_path(personal_request)%>
    </h1>
    <h2><%= (current_user == personal_request.user) ? "è una tua richiesta" : "di #{personal_request.user.login}" %></h2>
  </div>
  <div class="proposals">
    <%= personal_request.proposals.count %> proposte<br/>

    <% best_one = personal_request.best_proposal %>
    <% unless best_one.nil? %>
      <strong><%= best_one.amount %>&nbsp;&euro; la preferita</strong><br/>
    <% end %>

    <% unless current_user == personal_request.user %>
      <%= link_to 'Invia la tua proposta', proposal_new_path(personal_request) %>
    <% end %>

  </div>
  <div class="times">
    <strong>
      <% if personal_request.is_expired %>
        <%= "scaduta da #{distance_of_time_in_words DateTime.now, personal_request.expiration}" %>
      <% else %>
        <%= "scade tra #{distance_of_time_in_words DateTime.now, personal_request.expiration}" %>
      <% end %>
    </strong>
    <%= personal_request.expiration.strftime("%d/%m/%Y %H:%M") %>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div id="search_form">
  <%=form_tag( (url_for :controller=>:site, :action=>:index), :method=>:get )  do |f| %>
    <%= text_field_tag :query, search_bar.query, :placeholder => 'cerca' %>
    <%= select_tag :category_key.to_s, options_from_collection_for_select(Category.root.accept(OptionsVisitor.new).options, 'id', 'value', search_bar.category_key) %>
    <%= submit_tag "cerca", :id=>:search_button%>
  <%end%>
</div>

app/views/shared/_site_request.html.erb
<% if defined?(small).nil?
  small = false;
end %>

<% if small%>
  <table class="request">
    <tr>
      <td class="details">
        <%= link_to site_request.title, request_detail_path(site_request) %>
        <br/>
        <%= (current_user == site_request.user) ? "è una tua richiesta" : "di #{site_request.user.login}" %>
      </td>
      <td class="proposals">
        <%= site_request.proposals.count %> proposte<br/>

        <% best_one = site_request.best_proposal %>
        <% unless best_one.nil? %>
          <strong><%= best_one.amount %>&nbsp;&euro; la preferita</strong><br/>
        <% end %>

        <% unless current_user == site_request.user %>
          <%= link_to 'Invia la tua proposta', proposal_new_path(site_request) %>
        <% end %>
      </td>
      <td class="times">
        <strong>Scade tra <%=  distance_of_time_in_words DateTime.now, site_request.expiration%></strong>
        <%= site_request.expiration.strftime("%d/%m/%Y %H:%M") %>
      </td>
    </tr>
  </table>
<% else%>
  <table class="request">
    <tr>
      <td rowspan="2" class="picture">
        <%= image_tag "category/#{site_request.category_id}.jpg" %>
      </td>
      <td class="details">
        <h1><%= link_to site_request.title, request_detail_path(site_request) %></h1>
        <h2><%= (current_user == site_request.user) ? "è una tua richiesta" : "di #{site_request.user.login}" %></h2>
      </td>
      <td class="proposals">
        <%= site_request.proposals.count %> proposte<br/>

        <% best_one = site_request.best_proposal %>
        <% unless best_one.nil? %>
          <strong><%= best_one.amount %>&nbsp;&euro; la preferita</strong><br/>
        <% end %>

        <% unless current_user == site_request.user %>
          <%= link_to 'Invia la tua proposta', proposal_new_path(site_request) %>
        <% end %>
      </td>
      <td class="times">
        <strong>Scade tra <%=  distance_of_time_in_words DateTime.now, site_request.expiration%></strong>
        <%= site_request.expiration.strftime("%d/%m/%Y %H:%M") %>
      </td>
    </tr>
    <tr>
      <td colspan="3" class="description">
        <%= site_request.description %>
      </td>
    </tr>
  </table>
<% end %>

<!--
<% if small%>
  <div class="request">
    <div class="details">
      <h1><%= link_to site_request.title, request_detail_path(site_request) %></h1>
      <h2><%= (current_user == site_request.user) ? "è una tua richiesta" : "di #{site_request.user.login}" %></h2>
    </div>
    <div class="proposals">
      <%= site_request.proposals.count %> proposte<br/>

      <% best_one = site_request.best_proposal %>
      <% unless best_one.nil? %>
        <strong><%= best_one.amount %>&nbsp;&euro; la preferita</strong><br/>
      <% end %>

      <% unless current_user == site_request.user %>
        <%= link_to 'Invia la tua proposta', proposal_new_path(site_request) %>
      <% end %>

    </div>
    <div class="times">
      <strong><%=  distance_of_time_in_words DateTime.now, site_request.expiration%></strong>
      <%= site_request.expiration.strftime("%d/%m/%Y %H:%M") %>
    </div>
  </div>
<% else%>
  <div class="request">
    <div class="picture">
      <%= image_tag "category/#{site_request.category_id}.jpg" %>
    </div>
    <div class="details">
      <h1><%= link_to site_request.title, request_detail_path(site_request) %></h1>
      <h2><%= (current_user == site_request.user) ? "è una tua richiesta" : "di #{site_request.user.login}" %></h2>
    </div>
    <div class="proposals">
      <%= site_request.proposals.count %> proposte<br/>

      <% best_one = site_request.best_proposal %>
      <% unless best_one.nil? %>
        <strong><%= best_one.amount %>&nbsp;&euro; la preferita</strong><br/>
      <% end %>

      <% unless current_user == site_request.user %>
        <%= link_to 'Invia la tua proposta', proposal_new_path(site_request) %>
      <% end %>

    </div>
    <div class="times">
      <strong><%=  distance_of_time_in_words DateTime.now, site_request.expiration%></strong>
      <%= site_request.expiration.strftime("%d/%m/%Y %H:%M") %>
    </div>
  </div>
<% end %>
-->

app/views/shared/_site_request_old.html.erb
<div class="request">
  <h1>
    <%= link_to site_request.title, request_detail_path(site_request) %>
    <small>
      <%= (current_user == site_request.user) ? "è una tua richiesta" : "di #{site_request.user.login}" %>
    </small>
  </h1>
  <div class="request_body">

    <div class="request_picture">
      <img src="apartment.jpg" alt=""/>
    </div>

    <div class="request_highlight">

      <% if site_request.proposals.count > 0 %>

        Proposte: <strong><%= site_request.proposals.count %></strong><br/>

        <% best_one = site_request.best_proposal %>
        <% unless best_one.nil? %>
          La preferita: <strong><%= best_one.amount %>&nbsp;&euro; di <%= best_one.user.login %></strong><br/>
        <% end %>

      <% else %>
        Non ci sono ancora proposte.<br/>
      <% end %>
      <% unless current_user == site_request.user %>
        <%= link_to 'Invia la tua proposta', proposal_new_path(site_request) %>
      <% end %>
    </div>
    <%= site_request.description %>

    <table>
      <tr>
        <th>Data di creazione</th>
        <th>Data di scadenza</th>
        <th>Proposte</th>

      </tr>
      <tr>
        <td><%= site_request.updated_at.strftime("%d/%m/%Y") %></td>
        <td><%= site_request.expiration.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= site_request.proposals.count %></td>
      </tr>
    </table>

  </div>

</div>

app/views/shared/_slideshow.html.erb
<div class="slideshow">

  <%# slide per richiedenti %>
  <div class="slide">
    <h1>Sei in cerca di un operatore ?</h1>
    <div style="background-image: url(/images/slide-background-user.png); background-repeat: no-repeat; background-position: right;">
      <div class="content" style="margin-right: 170px">
        Vuoi trovare una baby sitter affidabile ? Un avvocato competente ? Un elettricista economico ?
        Inserisci la tua richiesta su MiServe.eu ed entra in contatto
        con tutti gli operatori iscritti.<br/>
        Inizia subito...
        <ol>
          <li><p>Registrati</p></li>
          <li><p>Inserisci la tua richiesta</p></li>
          <li><p>Aspetta le proposte dagli operatori</p></li>
          <li><p>Entra in contatto con l'operatore che consideri migliore</p></li>
        </ol>
      </div>
    </div>
  </div>

  <%# slide per operatori %>
  <div class="slide">
    <h1>Trova nuovi clienti</h1>
    <div style="margin: 0; padding: 0; background-image: url(/images/slide-background-operator.png); background-repeat: no-repeat; background-position: left;">
      <div class="content" style="margin-left: 170px">
        Sei un imbianchino e vuoi trovare appartamenti
        da ritinteggiare ?
        Sei una baby sitter e vuoi trovare famiglie
        che hanno bisogno del tuo aiuto ?
        Sei uno studente universitario e vuoi trovare
        studenti a cui fare ripetizioni ?
        <ol>
          <li><p>Registrati</p></li>
          <li><p>Cerca le proposte in linea con il tuo profilo</p></li>
          <li><p>Inserisci una proposta</p></li>
          <li><p>Entra in contatto con i clienti che ti hanno scelto</p></li>
        </ol>
      </div>
    </div>
  </div>

  <%# slide per l'accordo %>
  <div class="slide">
    <h1>Entra in contatto solo con i migliori</h1>
    <div style="background-image: url(/images/slide-background-shaking-hand.png); background-repeat: no-repeat; background-position: right;">
      <div class="content" style="margin-right: 170px">
        I dati di contatto dell'operatore e del cliente saranno
        resi vicendevolmente disponibili solo al termine del periodo
        di valutazione delle proposte indicato e solo se
        una delle richieste è stata considerata come la migliore.
      </div>
    </div>
  </div>

  <%# slide per ricerca %>
  <div class="slide">
    <h1>Trova nuovi lavori</h1>
    <div style="background-image: url(/images/slide-background-search.png); background-repeat: no-repeat; background-position: left;">
      <div class="content" style="margin-left: 170px">
          Gli operatori possono trovare le richieste presenti su MiServe.eu attraverso
          il motore di ricerca, o attraverso il sistema di segnalazione
          automatica nella propria area riservata.<br/>
          E' sufficiente descrivere le categorie alle quali si è interessati
          per ricevere una mail di avviso ogni volta che una nuova
          richiesta corrisponde.
      </div>
    </div>
  </div>  
  
</div> 