config/routes.rb
Estimating::Application.routes.draw do

	root :to => "static#index"
  match 'how_it_works' => 'static#how_it_works'
  match 'info/:action' => 'static'
  match 'sitemap.xml' => 'static#sitemap'

  match 'index(/:category_key)' => 'site#index', :as => :index, :category_key => /.+/
  match 'request_detail/:id' => 'site#request_detail', :as => :request_detail
  match 'proposal_submission' => 'site#proposal_submission', :as => :proposal_submission
  match 'proposal_new/:id' => 'site#proposal_new', :as => :proposal_new

  resources :requests
  match 'personal_index' => 'requests#personal_index'
  match 'search_requests' => 'requests#search'
  match 'set_best_proposal' => 'requests#set_best_proposal', :as => :set_best_proposal, :via => :post

  resources :proposals

  resources :favourite_categories
  match 'interesting_requests' => 'favourite_categories#interesting_requests', :as => :interesting_requests

  resources :users
  resources :user_sessions
	match 'login' => 'user_sessions#new'
	match 'logout' => 'user_sessions#destroy'
  match 'activation' => 'user_sessions#activation' # Shows the form in which the user could paste the activation code
  match 'activate' => 'user_sessions#activate' # Activate the account
  match 'lost_password' => 'users#lost_password'
  match 'require_reset_password_token' => 'users#require_reset_password_token' # Send an email with info about how to reset the pwd
  match 'confirm_password_reset' => 'users#confirm_password_reset'
  match 'password_reset' => 'users#password_reset'

end

app/models/request.rb
# A request issued by someone to find an operator that will provide a service.
#
# A request has a status (or publication status) that states if it is
# a draft (:draft) or if it is published (:active).
class Request < ActiveRecord::Base

	belongs_to :user	# foreign key: user_id
  has_many :proposals

  # Pagination
  cattr_reader :per_page
  @@per_page = 10

  validates_presence_of :title, :description, :expiration, :category_id
  validate :expiration_date_cannot_be_in_the_past

  after_initialize :ensure_default_values

  attr_accessor :eula

  def is_draft
    self.status == :draft.to_s
  end

  def is_active
    (self.status == :active.to_s) && (DateTime.now < self.expiration)
  end

  def is_expired
    (self.status == :active.to_s) && (DateTime.now >= self.expiration)
  end

  def can_be_modified?
    return !(self.is_active || self.is_expired)
  end

  # A Request is "awarded" when a proposal has been selected as best by the Request's owner
  # and when it is expired.
  # An awarded Request should not be modified and the Request's owner and best bid's owner
  # should be granted access to each other contact data.
  def awarded?
    return is_expired && !best_proposal.nil?
  end

  def self.find_drafts(user=nil)
    if user.nil?
      Request.where('status = :status', :status => :draft)
    else
      Request.where('user_id = :user_id AND status = :status', :user_id => user.id, :status => :draft)
    end
  end

  def self.find_active(user=nil)
    if user.nil?
      Request.where('status=:status AND :now<expiration', :status => :active, :now => DateTime.now)
    else
      Request.where('user_id = :user_id AND status=:status AND :now<expiration', :user_id => user.id, :status => :active, :now => DateTime.now)
    end
  end

  def self.find_expired(user=nil)
    if user.nil?
      Request.where('status=:status AND :now>=expiration', :user_id => user.id, :status => :active, :now => DateTime.now)
    else
      Request.where('user_id = :user_id AND status=:status AND :now>=expiration', :user_id => user.id, :status => :active, :now => DateTime.now)
    end
  end

  def best_proposal
    proposals = Proposal.where('request_id = :request_id AND is_best = :is_best', {:request_id => self.id, :is_best => true})
    if proposals.nil? || proposals.count == 0
      return nil
    else
      return proposals[0]
    end
  end

  def unloved_proposals
    Proposal.where('request_id = :request_id AND is_best = :is_best', {:request_id => self.id, :is_best => false})
  end

  def expiration_date_cannot_be_in_the_past
    errors.add(:expiration, I18n.t('activerecord.errors.models.request.attributes.expiration.in_the_past')) if !expiration.blank? and expiration< Date.today
  end

  protected

  def ensure_default_values
    self.expiration = DateTime.now + 15 if self.expiration.nil?
    self.status = :draft if self.status.blank?
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def search
    
  end

  def search_old
    #@requests.where('description like :term and user_id not in :user_id')
  end

  def new
    @request = Request.new
  end

  def show
    @request = Request.find(params[:id])

    # the request is alive, users can submit offers
    if @request.is_active
      the_action = :new_active

    # the request is expired and the owner has choose a best offer
    elsif @request.awarded?
      the_action = :new_awarded

    # the request is expired but the owner has not yet choosed the best offer
    elsif @request.is_expired
      the_action = :new_expired

    #the request is being edited and only the owner might access it.
    elsif @request.is_draft
      raise "Unauthorized" if current_user != @request.user
      the_action = :new
    end
    render :action => the_action
  end

  def create

    # set all values
    @request = Request.new(params[:request])

    # set the owner to the current logged user
    @request.user = current_user

    # set the expiration date
    begin
      unless params[:expiration_date].blank?
        @request.expiration= DateTime.strptime(params[:expiration_date], "%d/%m/%Y")
      end
    rescue
      @request.expiration= nil
    end

    # set the new status
    if params[:store_action] == :save.to_s
      @request.status = :draft
    elsif params[:store_action] == :publish.to_s
      @request.status = :active
    else
      raise "Unknown value '#{params[:store_action]}' for parameter #{:store_action}"
    end

    # if eula is not checked for publication, show it
    @request.valid? #this is to trigger validation
    if(params[:store_action] == :publish.to_s && params[:eula]!=:accepted.to_s )
      @request.errors[:eula]= I18n.t('activerecord.errors.models.request.attributes.eula.should_be_checked_for_publication')
      flash.now[:error]= "Si sono verificati degli errori."
      render :action => :new
      return
    end

    if @request.save
      flash.now[:notice]= "La tua richiesta è stata memorizzata. Ricordati di attivarla."
      render :action => :new
      return
    else
      flash.now[:error]= "Si sono verificati degli errori."
      render :action => :new
      return
    end
  end

  def update
    @request = Request.find(params[:id])
    @request.user = current_user
    if params[:store_action] == :save.to_s
      @request.status = :draft
    elsif params[:store_action] == :publish.to_s
      @request.status = :active
    else
      raise "Unknown value '#{params[:store_action]}' for parameter #{:store_action}"
    end
    begin
      unless params[:expiration_date].nil?
        @request.expiration= Date.strptime(params[:expiration_date], "%d/%m/%Y")
      end
    rescue
      @request.expiration= nil
    end

    if @request.update_attributes(params[:request])
      flash[:notice]= "La tua richiesta è stata aggiornata."
      redirect_to :action => :new
    else
      flash.now[:error]= "Si sono verificati degli errori."
      render :action => :new
    end
  end





  def index
    per_page = 5

    sorting = {
      'expiring_asc' => 'expiration asc',
      'published_desc' => 'updated_at desc',
      nil => 'expiration asc'
    }

    if params[:status] == :draft.to_s
      @title="Richieste in fase di costruzione"
      @subtitle="Elenco delle tue richieste ancora non pubblicate."
      @requests = Request \
        .where('user_id = :user_id', :user_id => current_user.id) \
        .where('status = :status', :status => :draft) \
        .order(sorting[params[:sorting]]) \
        .paginate( :page => params[:page], :per_page => per_page )
    elsif params[:status] == :active.to_s
      @title="Richieste attive"
      @subtitle="Elenco delle tue richieste pubblicate che stanno ricevendo offerte da parte degli operatori."
      @requests = Request \
        .where('user_id = :user_id', :user_id => current_user.id) \
        .where('status = :status', :status => :active) \
        .where(':now<expiration', :now => DateTime.now) \
        .order(sorting[params[:sorting]]) \
        .paginate( :page => params[:page], :per_page => per_page )
    elsif params[:status] == :expired.to_s
      @title="Richieste scadute"
      @subtitle="Richieste scadute, clicca sul titolo della richiesta per entrare in contatto con il miglior operatore."
      @requests = Request \
        .where('user_id = :user_id', :user_id => current_user.id) \
        .where('status = :status', :status => :active) \
        .where(':now>=expiration', :now => DateTime.now) \
        .order(sorting[params[:sorting]]) \
        .paginate( :page => params[:page], :per_page => per_page )
    else
      raise "'#{:status}' parameter with value '#{params[:status]}' not recognized."
    end
  end






  

  def personal_index
    if(current_user!=nil)
      @user = current_user
      favs = @user.favourite_categories
      unless favs.nil? || favs.empty?
        keys = favs.map do |fav|
          fav.category
        end
        @requests = Request \
          .where(:category_id => keys) \
          .where('user_id <> :user_id', :user_id => current_user.id) \
          .where('status = :status', :status => :active) \
          .where(':now<expiration', :now => DateTime.now) \
          .order('expiration asc')
      end
    else
      render :action => :index
    end
  end

  def set_best_proposal
    @request = Request.find(params[:request_id])
    best_id = params[:proposal_id]
    flash.now[:notice] = "Per la tua richiesta nessuna proposta è indicata come migliore."
    @request.proposals.each do |proposal|
      current_status = proposal.is_best
      next_status = (best_id.nil? || best_id.blank?) ? false : (best_id.to_s == proposal.id.to_s)
      if current_status != next_status

        # This is the proposal that was the best and
        # it is going to be discarded
        if proposal.is_best
          #TenderMailer.tender_proposal_discarded_as_best(@request, proposal)
          TenderMailer.delay.tender_proposal_discarded_as_best(@request, proposal)
          flash.now[:notice] = "La proposta di #{proposal.user.login} è ora la proposta migliore."
        end

        proposal.is_best = next_status

        # This is the proposal that is going to become the best
        proposal.save
        if proposal.is_best
          TenderMailer.delay.tender_proposal_choosen_as_best(@request, proposal)
          flash.now[:notice] = "La proposta di #{proposal.user.login} è ora la proposta migliore."
        end
      end
    end
    render :action => :new
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    $j(document).ready(function(){
      $j("#sorting").change(function(){
        $j(this).closest("form").submit();
      })
    });
  </script>
<% end %>

<div id="layout_side_main">

  <h3><%= @title %></h3>
  <p><%= @subtitle %></p>

  <div id="top_pagination">

    <%=form_tag( (url_for :controller=>:requests, :action=>:index), :method=>:get, :style=> 'display: inline' )  do |f| %>
      <% params.each do |key,value| %>
        <% if key!='sorting' %>
          <%= hidden_field_tag key, value %>
        <% end %>
      <% end %>
      mostra prima:
      <%= select_tag \
        :sorting, \
        options_for_select({
          "in scadenza" => :expiring_asc,
          "appena pubblicata" => :published_desc }, params[:sorting]) %>
    <%end%>

    <%= my_page_entries_info @requests %>
  </div>

  <%unless @requests.nil? || @requests.count == 0  %>
    <div class="requests">
    <%@requests.each do |request|%>
      <%= render :partial => 'shared/personal_request', :object => request %>
    <%end%>
    </div>
  <%else%>
    Non ci sono elementi in questo elenco
  <%end%>

  <div id="bottom_pagination">
    <%= will_paginate @requests, :previous_label => '&laquo;', :next_label => '&raquo;', :container => false %>
  </div>
    
</div>

app/views/requests/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag ['jquery.ui.datepicker-it'] %>
  <script type="text/javascript">

    function submitWithStoreAction(action){
      document.getElementById('store_action').value=action;
    }
    
    $j(document).ready(function(){

      // set up date picker
      $j( "#expiration_date" ).datepicker({
        dateFormat: 'dd/mm/yy',
        defaultDate: '<%=@request.expiration!=nil ? @request.expiration.strftime("%d/%m/%Y") : ''%>',
        changeMonth: true,
        changeYear: true
      })

      // set up the two submit buttons
      $j("#btn_save").click(function(){
        submitWithStoreAction('save');
      });
      $j("#btn_publish").click(function(){
        submitWithStoreAction('publish');
      });
    });
  </script>
<% end %>

<div id="layout_side_main">

  <% if @request.can_be_modified? %>

    <%= form_for(@request, :html=>{:class => :pretty}) do |f| %>

      <%=hidden_field_tag 'store_action'%>

      <fieldset>
        <legend>Dettagli della richiesta</legend>
        <div class="notes">
          <h4>Descrivi le tue necessità</h4>
          <p class="last">
            Più dettagli includerai più sarà
            semplice per gli operatori presentarti delle offerte in linea con la tua richieste.
          </p>
        </div>
        <div class="required">
          <%= f.label :title, 'Titolo:' %>
          <%= f.text_field :title, :class=>:inputText, :size=>10, :maxlength=>100 %>
          <small class="error"><%= @request.errors[:title].join(". ") %></small>
          <small>Il titolo permette di identificare la tua richiesta</small>
        </div>

        <div class="required">
          <%= f.label :description, 'Descrizione:' %>
          <%= f.text_area :description, :class=>:inputTextarea, :rows=>10, :cols=>21 %>
          <small class="error"><%= @request.errors[:description].join(". ") %></small>
          <small>Descrivi il servizio di cui necessiti ed ogni ulteriore informazione che pensi
            possa essere utile ad un operatore per proporti un'offerta.</small>
        </div>

        <div class="required">
          <%= f.label :expiration_date, 'Data di scadenza:' %>
          <%= text_field_tag :expiration_date, @request.expiration!=nil ? @request.expiration.strftime("%d/%m/%Y") : '', :class=>:inputText, :size=>10, :maxlength=>100 %>
          <small class="error"><%= @request.errors[:expiration].join(". ") %></small>
          <small>Data entro la quale vorresti essere messo in contatto con gli operatori.</small>
        </div>

        <div class="required">
          <%= label_tag :category_id, "Categoria:" %>
          <%= collection_select(:request, :category_id, Category.root.accept(OptionsVisitor.new).options, 'id', 'value', {:prompt=>true}, {:class=>:selectOne} ) %>
          <small class="error"><%= @request.errors[:category_id].join(". ") %></small>
          <small>La categoria aiuta gli operatori a selezionare le richieste nel loro settore.</small>
        </div>

      </fieldset>


      <fieldset>
        <legend>Pubblicazione</legend>
        <div class="notes">
          <h4>Pubblicazione</h4>
          <p>
            Premendo "Salva Bozza" la tua richiesta viene salvata nella tua area privata
            e non sarà visibile sino a quando non deciderai di pubblicarla.
          </p>
          <p class="last">
            Quando hai apportato tutte le modifiche puoi pubblicare la tua
            richiesta per renderla visibile agli operatori premendo "Pubblica".
            Attenzione, da questo momento in poi non potrai più ne rimuovere ne modificare
            la tua richiesta.
          </p>
        </div>
        <div class="optional">
          <%= f.label :btn_save, 'Salva come bozza:' %>
          <button id="btn_save" value="Salva">Salva Come Bozza</button>
          <small>Salvando la richiesta come bozza, questa non sarà pubblicata sul sito e potrai modificarla ulteriormente.</small>
        </div>
        <div class="optional">
          <%= label_tag :btn_save, "Pubblica:" %>
    <%# f.label :eula, 'Condizioni:' %>
          <%= check_box_tag :eula, :accepted, false, :class=>:checkBox %> Accetto le condizioni di pubblicazione.
          <small class="error"><%= @request.errors[:eula].join(". ") %></small>
          <small>Le condizioni di pubblicazione sono specificate nelle <%= link_to "condizioni d'uso", {:controller=>:static, :action=>:terms_of_service}, :target=>'_blank' %></small>
        </div>
        <div class="optional">
          <label>&nbsp;</label>
          <button id="btn_publish" value="Pubblica">Pubblica</button>
          <small>Quando pubblichi una richiesta questa viene resa disponibile sul sito a tutti gli operatori.</small>
        </div>
      </fieldset>

    <% end %>

  <% else %>
    <%= render :partial => 'shared/personal_request', :object => @request %>
  <% end %>


  <% all_proposals = @request.proposals %>
  <% best = @request.best_proposal %>

<%# box to show the current best proposal %>
<% unless @request.is_draft %>
  <%= render :partial => 'shared/best_proposal', :object => best %>
<% end %>




<%# box to chose the favourite proposal if request is active %>


  <% if @request.is_active %>
    <% unless all_proposals.nil? || all_proposals.count==0
      there_is_a_best_proposal = false%>
      <div class="box">
        <h1>
          Elenco offerte ricevute<br/>
          <small>
            Quando ricevi una nuova offerta che ti sembra più vantaggiosa puoi indicarla come tale in modo da sollecitare la concorrenza
            tra gli operatori.
          </small>
        </h1>
        <div class="body">
          <%= form_tag(set_best_proposal_path, :method => :post)  do |f| %>
            <%= hidden_field_tag 'request_id', @request.id %>
            <% all_proposals.each do |proposal|
              there_is_a_best_proposal = there_is_a_best_proposal || proposal.is_best %>

              <table>
                <tr>
                  <td colspan="2"><%= radio_button_tag :proposal_id, proposal.id, proposal==best %>
                    Scegli questa come offerta milgiore</td>
                </tr>
                <tr>
                  <td>Operatore</td>
                  <td><%= proposal.user.login %></td>
                </tr>
                <tr>
                  <td>Preventivo</td>
                  <td><%= proposal.amount %> &euro;</td>
                </tr>
                <tr>
                  <td>Descrizione</td>
                  <td><%= proposal.description %></td>
                </tr>
              </table>
            <%end%>

            <table>
              <tr>
                <td colspan="2"><%= radio_button_tag :proposal_id, '', !there_is_a_best_proposal %>
                  Non mi piace nessuna offerta.</td>
              </tr>
            </table>
            <input type="submit" value="scegli la nuova offerta preferita"/>
          <% end %>
        </div>
      </div>
    <% end %>

  <% end %>



  <% if @request.is_expired and !all_proposals.nil? and all_proposals.length >= 1%>
    <% if best.nil? %>
      <div class="box">
        <h1>
          Elenco offerte ricevute<br/>
          <small>
            Scegli una delle offerte ricevute come migliore per entrare in contatto con il proponente.
          </small>
        </h1>
        <div class="body">
          <%= form_tag(set_best_proposal_path, :method => :post)  do |f| %>
            <%= hidden_field_tag 'request_id', @request.id %>
            <% all_proposals.each do |proposal|
              there_is_a_best_proposal = there_is_a_best_proposal || proposal.is_best %>

              <table>
                <tr>
                  <td colspan="2"><%= radio_button_tag :proposal_id, proposal.id, proposal==best %>
                    Scegli questa come offerta milgiore</td>
                </tr>
                <tr>
                  <td>Operatore</td>
                  <td><%= proposal.user.login %></td>
                </tr>
                <tr>
                  <td>Preventivo</td>
                  <td><%= proposal.amount %> &euro;</td>
                </tr>
                <tr>
                  <td>Descrizione</td>
                  <td><%= proposal.description %></td>
                </tr>
              </table>
            <%end%>

            <table>
              <tr>
                <td colspan="2"><%= radio_button_tag :proposal_id, '', !there_is_a_best_proposal %>
                  Non mi piace nessuna offerta.</td>
              </tr>
            </table>
            <input type="submit" value="seleziona l'offerta preferita per entrare in contatto con il proponente"/>
          <% end #form%>
        </div> <!-- .body -->
      </div>

    </div> <!-- .box -->
  <% end %>

  <% unless best.nil? %>
    <% best_proposer = best.user %>
    <div class="box">
      <h1>
        Dati per contattare l'offerente<br/>
        <small>
          Qui di seguito sono riportati i dati dell'operatore che si è aggiudicato l'erogazione del servizio da te richiesto.
        </small>
      </h1>
      <div class="body">
        <table>
          <tr><td>Nominativo:</td><td><%= best_proposer.first_name %> <%= best_proposer.last_name %></td></tr>
          <tr><td>Email:</td><td><%= best_proposer.email %></td></tr>
          <tr><td>Indirizzo:</td><td><%= best_proposer.address %> <%= best_proposer.zip %> <%= best_proposer.city %></td></tr>
          <tr><td>Utente professionale:</td><td><%= best_proposer.is_professional ? "si" : "no" %></td></tr>
          <% if best_proposer.is_professional %>
            <tr><td>Partita IVA:</td><td><%= best_proposer.vat %></td></tr>
            <tr><td>Ragione sociale:</td><td><%= best_proposer.company_name %></td></tr>
            <tr><td>Attività principale:</td><td><%= best_proposer.activity %></td></tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
<% end %>


<% if @request.is_expired and ( all_proposals.nil? or all_proposals.empty? )%>
  <div class="box">
    <h1>Elenco offerte ricevute</h1>
    <div class="body">
      Ci dispiace, ma nessun operatore ha fatto una proposta per
      la tua richiesta entro i termini di validità.
    </div>
  </div>
<% end %>

</div>

app/views/requests/new_active.html.erb
<%
# This view should be used to show a user its active requests.
# The view should give access to the following functionalities:
# * select the best proposal (if any);
# * show a list of current proposals (if any)
%>

<% all_proposals = @request.proposals %>
<% best = @request.best_proposal %>

<div id="layout_side_main">

  <h1>Richiesta attiva</h1>

  <%# box containing the request details %>
  <div class="box">
    <h1>Dettagli della richiesta</h1>
    <div class="body">
      <%= render :partial => 'shared/personal_request', :object => @request %>
      <%= @request.description %>
    </div>
  </div>

  <%= render :partial => 'shared/best_proposal', :object => best %>

  <% if current_user == @request.user %>
    <% unless all_proposals.nil? || all_proposals.count==0
      there_is_a_best_proposal = false%>
      <div class="box">
        <h1>
          Elenco offerte ricevute<br/>
          <small>
            Quando ricevi una nuova offerta che ti sembra
            più vantaggiosa puoi indicarla come tale
            in modo da sollecitare la concorrenza
            tra gli operatori.
          </small>
        </h1>
        <div class="body">
          <%= form_tag(set_best_proposal_path, :method => :post)  do |f| %>
            <%= hidden_field_tag 'request_id', @request.id %>
            <% all_proposals.each do |proposal|
              there_is_a_best_proposal = there_is_a_best_proposal || proposal.is_best %>

              <table>
                <tr>
                  <td colspan="2"><%= radio_button_tag :proposal_id, proposal.id, proposal==best %>
                    Scegli questa come offerta milgiore</td>
                </tr>
                <tr>
                  <td>Operatore</td>
                  <td><%= proposal.user.login %></td>
                </tr>
                <tr>
                  <td>Preventivo</td>
                  <td><%= proposal.amount %> &euro;</td>
                </tr>
                <tr>
                  <td>Descrizione</td>
                  <td><%= proposal.description %></td>
                </tr>
              </table>
            <%end%>

            <table>
              <tr>
                <td colspan="2"><%= radio_button_tag :proposal_id, '', !there_is_a_best_proposal %>
                  Nessuna delle proposte elencate è soddisfacente.</td>
              </tr>
            </table>
            <input type="submit" value="imposta la proposta selezionata come preferita"/>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="box">
      <h1>
        Elenco offerte presentate<br/>
        <small>
          Ecco qui la lista delle offerte presentate per questa richiesta.
          Fatti un idea e sottometti la tua offerta!
        </small>
      </h1>
      <div class="body">
        <% all_proposals.each do |proposal| %>
          <table>
            <tr>
              <td>Operatore</td>
              <td><%= proposal.user.login %></td>
            </tr>
            <tr>
              <td>Preventivo</td>
              <td><%= proposal.amount %> &euro;</td>
            </tr>
            <tr>
              <td>Descrizione</td>
              <td><%= proposal.description %></td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>

    <div class="box">
      <h1>
        Presenta la tua offerta<br/>
      </h1>
      <div class="body">
        <%=link_to 'Fai la tua proposta', proposal_new_path(@request) %>
      </div>
    </div>

  <% end %>


</div>

app/views/requests/new_expired.erb
<%
# This page shows expired requests and should be visible only to
# the owner and the awarded user
%>

<% all_proposals = @request.proposals %>
<% best = @request.best_proposal %>
<% there_are_proposals = !all_proposals.nil? and all_proposals.length >= 1 %>
<% a_best_offer_has_been_choosed = there_are_proposals && !best.nil? %>

<div id="layout_side_main">

  <%# box containing the request details %>
  <div class="box">
    <h1>Dettagli della richiesta</h1>
    <div class="body">
      <%= render :partial => 'shared/personal_request', :object => @request %>
      <%= @request.description %>
    </div>
  </div>
  
  <%= render :partial => 'shared/best_proposal', :object => best %>

  <%if current_user == @request.user %>


    <% unless a_best_offer_has_been_choosed %>
      <div class="box">
        <h1>
          Elenco offerte ricevute<br/>
          <small>
            Scegli una delle offerte ricevute come migliore per entrare in contatto con il proponente.
          </small>
        </h1>
        <div class="body">
          <%= form_tag(set_best_proposal_path, :method => :post)  do |f| %>
            <%= hidden_field_tag 'request_id', @request.id %>
            <% all_proposals.each do |proposal|
              there_is_a_best_proposal = there_is_a_best_proposal || proposal.is_best %>
              <table>
                <tr>
                  <td colspan="2"><%= radio_button_tag :proposal_id, proposal.id, proposal==best %>
                    Scegli questa come offerta milgiore</td>
                </tr>
                <tr>
                  <td>Operatore</td>
                  <td><%= proposal.user.login %></td>
                </tr>
                <tr>
                  <td>Preventivo</td>
                  <td><%= proposal.amount %> &euro;</td>
                </tr>
                <tr>
                  <td>Descrizione</td>
                  <td><%= proposal.description %></td>
                </tr>
              </table>
            <%end%>
            <input type="submit" value="seleziona l'offerta preferita per entrare in contatto con il proponente"/>
          <% end %>
        </div>
      </div>
    <% end %>


    <% if all_proposals.nil? or all_proposals.empty? %>
      <div class="box">
        <h1>Elenco offerte ricevute</h1>
        <div class="body">
          Ci dispiace, ma nessun operatore ha fatto una proposta per
          la tua richiesta entro i termini di validità.
        </div>
      </div>
    <% end %>

  <%end%>




</div>

app/views/requests/personal_index.html.erb
<p>
Benvenuto <%=@user.first_name%> <%=@user.last_name%>
</p>
<p>
  Questa è la tua area personale. Dal menù puoi controllare le richieste che hai inserito
  nel sistema, creare nuove richieste e vedere quali operatori ti hanno risposto.
</p>

<% unless @requests.nil? || @requests.empty? %>
  <div class="index_box">
    <h1>Richieste in scadenza</h1>
    <div>
      <div class="requests">
        <%@requests.each do |request|%>
          <%= render :partial => 'shared/site_request', :object => request, :locals => {:small => true} %>
        <%end%>
      </div>
    </div>
  </div>
<% end %>

app/views/requests/search.html.erb
<form>
  Ricerca <input type="text" name="search"/>
</form>
<table>
  <thead>
    
  </thead>
</table>