config/routes.rb
Estimating::Application.routes.draw do

	root :to => "static#index"
  match 'how_it_works' => 'static#how_it_works'
  match 'info/:action' => 'static'
  match 'sitemap.xml' => 'static#sitemap'

  match 'index(/:category_key)' => 'site#index', :as => :index, :category_key => /.+/
  match 'request_detail/:id' => 'site#request_detail', :as => :request_detail
  match 'proposal_submission' => 'site#proposal_submission', :as => :proposal_submission
  match 'proposal_new/:id' => 'site#proposal_new', :as => :proposal_new

  resources :requests
  match 'personal_index' => 'requests#personal_index'
  match 'search_requests' => 'requests#search'
  match 'set_best_proposal' => 'requests#set_best_proposal', :as => :set_best_proposal, :via => :post

  resources :proposals

  resources :favourite_categories
  match 'interesting_requests' => 'favourite_categories#interesting_requests', :as => :interesting_requests

  resources :users
  resources :user_sessions
	match 'login' => 'user_sessions#new'
	match 'logout' => 'user_sessions#destroy'
  match 'activation' => 'user_sessions#activation' # Shows the form in which the user could paste the activation code
  match 'activate' => 'user_sessions#activate' # Activate the account
  match 'lost_password' => 'users#lost_password'
  match 'require_reset_password_token' => 'users#require_reset_password_token' # Send an email with info about how to reset the pwd
  match 'confirm_password_reset' => 'users#confirm_password_reset'
  match 'password_reset' => 'users#password_reset'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index

    query = params[:query].nil? ? "" : params[:query]
    category_key = params[:category_key].nil? ? "" : params[:category_key]
    @search = Struct.new("Search", :query, :category_key).new(query,category_key)

    sorting = {
      'expiring_asc' => 'expiration asc',
      'published_desc' => 'updated_at desc',
      nil => 'expiration asc'
    }

    if @search.query.blank?
      @requests = Request \
        .where('status=:status AND :now<expiration', :status => :active, :now => DateTime.now) \
        .where('category_id like :category_id', :category_id => "#{@search.category_key}%") \
        .order(sorting[params[:sorting]]) \
        .paginate( :page => params[:page], :per_page => 10 )
    else
      @requests = Request \
        .where('status=:status AND :now<expiration', :status => :active, :now => DateTime.now) \
        .where("category_id like :category_id", :category_id => "#{@search.category_key}%") \
        .where("title like ?", '%' + @search.query + '%') \
        .order(sorting[params[:sorting]]) \
        .paginate( :page => params[:page], :per_page => 10 )
    end

    render :index
  end

  def request_detail
    @request = Request.find params[:id]
    set_visited_request(@request)
  end

  # Called when user want to submit a new proposal.
  # proposal_new/:id
  def proposal_new
    request = Request.find(params[:id])
    if ensure_login(request)
      @request = request
      @proposal = Proposal.new
      @proposal.request = @request
    end
  end

  def proposal_submission

    # If the user is logged in, then the proposal is saved else he is required
    # to login.
    # The id of the request he was currently watching is saved.
    if current_user
      @request = Request.find params[:request][:id]
      if @request.nil?
        raise "Requst with id #{params[:request][:id]} not found"
      end
      @proposal = Proposal.new(params[:proposal])
      @proposal.request = @request
      @proposal.user = current_user
      if @proposal.save

        #TenderMailer.tender_new_proposal_for_request_owner_email(@request, @proposal).deliver
        TenderMailer.delay.tender_new_proposal_for_request_owner_email(@request, @proposal)

        flash.now[:notice]='La tua offerta è stata registrata con successo. Puoi ora tenerla sotto controllo nella tua area personale'
      else
        flash.now[:error]='La tua offerta non è stata salvata'
      end
      render :action => :request_detail
    else
      render :require_login
    end
  end

  private

  def ensure_login(request=nil)
    unless request.nil?
      set_visited_request(request)
    end
    if current_user.nil?
      render :require_login
      return false
    else
      return true
    end
  end
  
end

app/views/site/how_it_works.erb
<h1>Come Funziona ?</h1>
<img style="float: left;" src="../images/plumber.jpg"/>
<img style="float: right;" src="../images/feedback.jpg"/>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a lectus felis.
  Nunc imperdiet lacinia velit. Nunc id augue nisl. Praesent in lacus velit.
  Pellentesque congue elementum urna.
  Fusce nunc neque, ultrices nec consectetur eget, rhoncus a urna.
  Etiam commodo, libero in elementum suscipit, magna sapien mattis elit, sit amet
  fermentum neque massa in quam. Aenean lobortis tincidunt scelerisque.
  Nulla dignissim tempor justo nec imperdiet.
</p>
<h2>Operatore</h2>
<p>
  Proin est leo, ultricies ac porta vitae, gravida ac nulla.
  Mauris interdum vulputate consequat. Mauris mattis sapien et ligula sagittis
  pellentesque nec sit amet quam. Quisque eget facilisis turpis.
  Phasellus feugiat tellus nisi. Proin convallis dapibus mi,
  id malesuada sem gravida vel. Proin id neque lacus.
  Duis dictum, odio id gravida ornare, metus urna tincidunt quam, vel tempor nibh enim vitae justo.
  Sed egestas leo auctor augue hendrerit porttitor.
</p>
<p>
  Vestibulum luctus accumsan iaculis.
  Donec sit amet orci ac urna mattis sollicitudin.
  Etiam sodales velit in tellus tristique sit amet tincidunt velit faucibus.
  In vel metus metus. Aenean id quam dolor.
  Sed sed mollis neque. Nulla id tellus volutpat nibh volutpat sodales
  quis nec lacus.
</p>
<h2>Fornitore</h2>
<p>
  Vivamus tellus velit, aliquam eu posuere ut, consectetur a ipsum.
  Ut et augue odio.
  Cras ante mauris, blandit ac condimentum quis, euismod ut massa.
  Mauris a est fermentum turpis aliquam sagittis.
  Sed non magna metus, at interdum lacus.
  Duis nec leo libero, adipiscing fermentum magna. Sed et neque neque.
  Quisque cursus aliquam risus nec feugiat.
  Curabitur sem ipsum, porttitor non hendrerit at, sagittis quis quam.
  Donec lacinia felis vel urna pellentesque in pulvinar libero porttitor.
</p>
<p>
  Proin est leo, ultricies ac porta vitae, gravida ac nulla.
  Mauris interdum vulputate consequat. Mauris mattis sapien et ligula sagittis
  pellentesque nec sit amet quam. Quisque eget facilisis turpis.
  Phasellus feugiat tellus nisi. Proin convallis dapibus mi,
  id malesuada sem gravida vel. Proin id neque lacus.
  Duis dictum, odio id gravida ornare, metus urna tincidunt quam, vel tempor nibh enim vitae justo.
  Sed egestas leo auctor augue hendrerit porttitor.
</p>
<p>
  Vestibulum luctus accumsan iaculis.
  Donec sit amet orci ac urna mattis sollicitudin.
  Etiam sodales velit in tellus tristique sit amet tincidunt velit faucibus.
  In vel metus metus. Aenean id quam dolor.
  Sed sed mollis neque. Nulla id tellus volutpat nibh volutpat sodales
  quis nec lacus.
</p>
<p>
  Vivamus tellus velit, aliquam eu posuere ut, consectetur a ipsum.
  Ut et augue odio.
  Cras ante mauris, blandit ac condimentum quis, euismod ut massa.
  Mauris a est fermentum turpis aliquam sagittis.
  Sed non magna metus, at interdum lacus.
  Duis nec leo libero, adipiscing fermentum magna. Sed et neque neque.
  Quisque cursus aliquam risus nec feugiat.
  Curabitur sem ipsum, porttitor non hendrerit at, sagittis quis quam.
  Donec lacinia felis vel urna pellentesque in pulvinar libero porttitor.
</p>

app/views/site/index.html.erb
<% 
unless @search.nil?
  @page_title = titlize("Proposte di lavori nella categoria '#{@search.query} #{Category.t_name_by_key(@search.category_key)}'")  
else
  @page_title = titlize("Proposte di lavori nella categoria '#{@search.query} #{Category.t_name_by_key(@search.category_key)}'")  
end
%>
<% @page_description = "Elenco degli appalti ancora aperti nella categoria '#{Category.t_name_by_key(@search.category_key)}'. I titolari delle richieste accettano nuovi preventivi." %>

<% content_for :head do %>
  <script type="text/javascript">
    $j(document).ready(function(){
      $j("#sorting").change(function(){
        $j(this).closest("form").submit();
      })
    });
  </script>
<% end %>

<% content_for :layout_side_two do %>
  <%= render :partial => 'shared/default_side_two'  %>
<% end %>

<%= render :partial => 'shared/search_bar', :object => @search %>

<%if !@requests.nil? && @requests.count>0 %>
  <div id="top_pagination">

    <%=form_tag( (url_for :controller=>:site, :action=>:index), :method=>:get, :style=> 'display: inline' )  do |f| %>
      <% params.each do |key,value| %>
        <% if key!='sorting' %>
          <%= hidden_field_tag key, value %>
        <% end %>
      <% end %>
      mostra prima:
      <%= select_tag \
        :sorting, \
        options_for_select({ 
          "in scadenza" => :expiring_asc,
          "appena pubblicata" => :published_desc }, params[:sorting]) %>
    <%end%>

    <%= my_page_entries_info @requests %>
  </div>

  <div class="requests">
    <%@requests.each do |request|%>
      <%= render :partial => 'shared/site_request', :object => request %>
    <%end%>
  </div>

  <div id="bottom_pagination">
    <%= will_paginate @requests, :previous_label => '&laquo;', :next_label => '&raquo;', :container => false %>
  </div>

<%else%>
  Non ci sono risultati per questa ricerca
<%end%>

<%= render :partial => 'shared/search_bar', :object => @search %>

app/views/site/proposal_new.html.erb
<% @page_title = titlize("Nuova proposta per '#{@request.title}'")  %>
<% @page_description = "Nuova offerta economica per l'appalto '#{@request.title}' nella categoria '#{Category.t_name_by_key(@request.category_id)}'." %>

<% content_for :layout_side_two do %>
  <%= render :partial => 'shared/default_side_two' %>
<% end %>

<p>
  Benvenuto <%= current_user.login %>,
  <br/>
  stai per sottomettere un'offerta relativa alla seguente richiesta:
  <br/>
  <%= render :partial => 'shared/site_request', :object => @request %>
</p>
<p>
  Ti ricordiamo che sottomettendo un'offerta ti impegni a portarla a termine
  nei modi, nei tempi, al costo e alle condizioni da te descritte nel caso
  la tua offerta risulti come la migliore al termine del periodo di valutazione, come
  specificato dalle condizioni d'utilizzo del sito.
</p>

<%= form_for @proposal, :url => proposal_submission_path, :html => {:class => :pretty} do |f| %>
  <%= hidden_field :request, 'id' %>
  <fieldset>
    <legend>Proposta</legend>
        <div class="notes">
          <h4>Proposta</h4>
          <p>
            Utilizza questa scheda per sottoporre la tua offerta. Le regole
            del sito prescrivono che tu garantisca l'esecuzione del lavoro
            secondo quanto da te descritto.
          </p>
          <p class="last">
            Inserisci inoltre il preventivo in modo che il richiedente possa
            valutare appieno la tua proposta.
          </p>
        </div>
    <div class="required">
      <%= f.label :description, 'Descrizione:' %>
      <%= f.text_area :description, :class=>:inputTextarea, :rows=>10, :cols=>21 %>
      <small class="error"><%= @proposal.errors[:description].join(". ") %></small>
      <small>Descrivi qui i termini della tua offerta.</small>
    </div>

    <div class="required">
      <%= f.label :amount, 'Ammontare in €:' %>
      <%= f.text_field :amount, :class=>:inputText, :size=>10, :maxlength=>100 %>
      <small class="error"><%= @proposal.errors[:amount].join(". ") %></small>
      <small>Inserisci il preventivo per la tua offerta in euro.</small>
    </div>

    <div class="optional">
      <%= f.label :btn_submit, 'Invia proposta' %>
      <%= submit_tag "Invia la tua proposta", :id=>:btn_submit %>
      <small>Premi qui per inviare la tua proposta.</small>
    </div>


  </fieldset>
<% end %>

app/views/site/request_detail.html.erb
<% @page_title = titlize("Dettagli della richiesta '#{@request.title}'")  %>
<% @page_description = "Dettagli dell'appalto '#{@request.title}' nella categoria '#{Category.t_name_by_key(@request.category_id)}'." %>

<% content_for :head do %>
  <script type="text/javascript" src="http://apis.google.com/js/plusone.js">
    {lang: 'it'}
  </script>
  <script src="http://connect.facebook.net/it_IT/all.js"></script>
  <script>
    FB.init({
      status : true,
      cookie : true,
      xfbml  : true
    });
  </script>
  <meta property="og:image" content="<%= request.protocol%><%= request.host%>:<%= request.port%><%= image_path "category/#{@request.category_id}.jpg" %>"/>
  <meta property="og:type" content="article"/>
  <meta property="og:site_name" content="Mi Serve"/>
<% end %>

<% content_for :layout_side_two do %>
  <%= render :partial => 'shared/default_side_two' %>
<% end %>



<%# box containing the request details %>

<div style="border: 0; margin: 0; padding: 0;">
  <div class="box" style="width: 610px; float: left; clear: none;">
    <h1>Dettagli della richiesta</h1>
    <div class="body">
      <%= render :partial => 'shared/site_request', :object => @request %>
      <%= @request.description %>
    </div>
  </div>
  <div style="border: 0; margin: 0 0 0 5px; padding: 0; float: left; width: 80px; text-align: left;">

    <% #Google +1 button  %>
    <g:plusone size="tall"></g:plusone>

    <% #Twitter button %>
    <a href="http://twitter.com/share" class="twitter-share-button" data-text="Trovato su miserve.eu:" data-count="vertical" data-lang="it">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

    <% #FB button %>
    <fb:like href="<%= request.url %>" layout="box_count" show-faces="false" width="80" action="like" colorscheme="light" />

  </div>
</div>



<%# box for placing a proposal %>
<div class="box">
  <h1>Sottoponi una proposta</h1>
  <div class="body">
    <% if @request.user != current_user %>
      <%= link_to "Nuova proposta", proposal_new_path(@request) %>
    <% else %>
      Questa è una tua richiesta! Non puoi fare offerte.
    <% end %>
  </div>
</div>


<%
best_proposal = @request.best_proposal
unloved_proposals = @request.unloved_proposals
there_are_proposals = (@request.proposals.count >= 1)
%>

<%# box for current best proposal %>
<%if there_are_proposals%>
  <%= render :partial => 'shared/best_proposal', :object => best_proposal %>
<%end%>

<%# box for unloved proposals %>
<div class="box">
  <h1>Proposte correnti</h1>
  <div class="body">
    <%if unloved_proposals.count >= 1%>
      Queste sono le altre proposte relative a quet'offerta
      <%unless (unloved_proposals.nil? || unloved_proposals.count == 0) %>
        <ul>
          <% unloved_proposals.each do |proposal| %>
              <table>
                <tr>
                  <td>Operatore</td>
                  <td><%= proposal.user.login %></td>
                </tr>
                <tr>
                  <td>Preventivo</td>
                  <td><%= proposal.amount %> &euro;</td>
                </tr>
                <tr>
                  <td>Descrizione</td>
                  <td><%= proposal.description %></td>
                </tr>
              </table>
          <% end%>
        </ul>
      <% end %>
    <% else %>
      Non ci sono altre proposte
    <%end%>
  </div>
</div>

app/views/site/require_login.html.erb
<% @page_title = titlize("Login")  %>

<% content_for :layout_side_two do %>
  <%= render :partial => 'shared/default_side_two' %>
<% end %>

<div class="index_box">
  <h1>Accedi con il tuo account</h1>
  Accedi con il tuo account o <%= link_to "registrati", new_user_path %> per crearne uno nuovo.
  <%= form_for UserSession.new do |form| %>
    <%= form.text_field :login %>
    <%= form.password_field :password %>
    <%= form.submit "login" %>
  <% end%>
</div>